version: '3.9'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:18.0.0
    restart: always
    env_file: ./keycloak/keycloak.env
    depends_on:
      - keycloak_db
    volumes:
      - ./keycloak/data/import:/opt/jboss/keycloak/imports
    command: -Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.import=/opt/jboss/keycloak/imports/realm.json start-dev
    ports:
      - '18080:8080'

  keycloak_db:
    container_name: keycloak_db
    image: mariadb:10.3.26
    restart: always
    volumes:
      - keycloak_db_vol:/var/lib/mysql
    env_file:
      - ./keycloak/keycloak.env

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=usersdb'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@gmail.com'
      - 'PGADMIN_DEFAULT_PASSWORD=password'
    ports:
      - '5050:80'
    depends_on:
      - postgres

volumes:
  pg_data:
  keycloak_db_vol:
